#########################################################
# Secrets
#########################################################
apiVersion: v1
kind: Secret
metadata:
  name: redis-credentials
type: Opaque
data:
  user: ZGVmYXVsdA==
  password: ZlN2VUJKaUpKNQ==

---

#########################################################
# Deployment
#########################################################
apiVersion: apps/v1
kind: Deployment
metadata:
  name: search-deployment
spec:
  selector:
    matchLabels:
      app: search-app
  replicas: 1
  template:
    metadata:
      labels:
        app: search-app
    spec:
      containers:
        - name: search-container
          image: searchapi:latest
          imagePullPolicy: Always
          env:
            - name: RedisConnectionString
              value: "cacheserver-redis-master.caching.svc.cluster.local:6379"
            - name: REDISUSER
              valueFrom:
                secretKeyRef:
                  name: redis-credentials
                  key: user
            - name: REDISPASSWORD
              valueFrom:
                secretKeyRef:
                  name: redis-credentials
                  key: password
            - name: LOKI_HOSTNAME
              value: "http://loki-headless.grafana-loki.svc.cluster.local:3100"
            - name: OTEL_RESOURCE_ATTRIBUTES
              value: "service.name=weatherforecast-service,service.namespace=default,service.version=1.0,service.instance.id=`uuidgen`,host.name=`HOSTNAME`,host.type=`uname -m`,os.name=`uname -s`,os.version=`uname -r`"
          ports:
            - containerPort: 8080

---

#########################################################
# Service
#########################################################
apiVersion: v1
kind: Service
metadata:
  labels:
    app: search-service
  name: search-service
  annotations:
    prometheus.io/port: "metrics"
    prometheus.io/scrape: "true"
spec:
  type: ClusterIP
  selector:
    app: search-app
  ports:
    - name: "metrics"
      port: 8080
---

#########################################################
# Prometheus Service Monitor
#########################################################
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: search-service-monitor
  namespace: monitoring
  labels:
    app: search-service
    release: kube-prometheus-stack
spec:
  namespaceSelector:
    matchNames:
      - default
  selector:
    matchLabels:
      app: search-service
  endpoints:
    - interval: 15s
      port: metrics
---
